name: Release Nuget Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Generate Nuget Packages
        run: |
          Remove-Item Directory.Build.props
          Rename-Item -Path Github.Directory.Build.props -NewName Directory.Build.props
          cd .\BuildSdk
          dotnet build -c Release
          dotnet pack -c Release -o packages\ --include-source --include-symbols --no-build
          
      - name: Install NuGet Client
        uses: nuget/setup-nuget@v1
        
      - name: Remove Github NuGet Source
        run: dotnet nuget remove source github
        
      - name: Add Github NuGet Source
        run: dotnet nuget add source --username byCrookie --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/byCrookie/index.json"
        
      - name: Push NuGet Packages To Github Packages
        run: nuget push .\BuildSdk\packages\*.nupkg -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source github -SkipDuplicate
